#!/bin/sh

BUILD_TYPE=${BUILD_TYPE:-Debug}

BUILD_DIR="${BUILD_TYPE}"

mkdir -p .build
cd .build

if [ "$(uname)" = "FreeBSD" ] && [ -z "$CI" ]
then
	export PATH=/usr/local/llvm20/bin:$PATH
	export CC=$(which clang)
	export CXX=$(which clang++)
fi

if [ ! -f "${BUILD_DIR}/build.ninja" ]
then
	cmake \
		-G "Ninja" \
		-B ${BUILD_DIR} \
		-DCMAKE_TOOLCHAIN_FILE=../../cmake/linux.cmake \
		-DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
		-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
		../
fi

cmake --build ${BUILD_DIR}
