#!/bin/sh -e

source="$1"
shift 1
flags="$@"

object="$OBJ_DIR/$source.o"

if [ ! -f "$object" ] || [ "$source" -nt "$object" ]
then
	mkdir -p $(dirname "$object")
	case "$source" in
		*.c)
			exec $CC $flags -c "$source" -o "$object"
			;;
		*.cpp)
			exec $CXX $flags -c "$source" -o "$object"
			;;
		*)
			echo "Cannot compile $source"
			exit 1
			;;
	esac
fi
