#!/bin/sh -e

cc="$1"
cxx="$2"
source="$3"
object="$4"
shift 4
flags="$@"

if [ ! -f "$object" ] || [ "$source" -nt "$object" ] || [ "./build" -nt "$object" ]
then
	mkdir -p $(dirname "$object")
	case "$source" in
		*.c)
			exec $cc $flags -c "$source" -o "$object"
			;;
		*.cpp)
			exec $cxx $flags -c "$source" -o "$object"
			;;
		*)
			echo "Cannot compile $source"
			exit 1
			;;
	esac
fi
