#!/bin/sh -e

./build $@ || true
export BUILD_TYPE=${1:-Debug}
export PLATFORM=${2:-linux}
./test $@ || true

inotifywait -r -e CLOSE_WRITE -m build src tests | \
	while read path action file
	do
		printf '%*s\n' "$(tput cols)" '' | tr ' ' -
		if ./build $@
		then
			./test $@ || true
		fi
	done
